# Generated by Django 5.1.2 on 2024-11-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_image',
            field=models.ImageField(default='default.jpg', upload_to='train_images/'),
        ),
    ]
